using Bridge;
using System.Collections.Generic;

namespace Weapon
{
	internal static class WeaponResources
	{
		public static readonly ItemInfo[] WeaponsInfos = [
			new ("小刀", "WEAPON_KNIFE"),
			new ("警棍", "WEAPON_NIGHTSTICK"),
			new ("铁锤", "WEAPON_HAMMER"),
			new ("棒球棒", "WEAPON_BAT"),
			new ("高尔夫球杆", "WEAPON_GOLFCLUB"),
			new ("撬棍", "WEAPON_CROWBAR"),
			new ("手枪", "WEAPON_PISTOL"),
			new ("战斗手枪", "WEAPON_COMBATPISTOL"),
			new ("穿甲手枪", "WEAPON_APPISTOL"),
			new ("0.5口径手枪", "WEAPON_PISTOL50"),
			new ("微型冲锋枪", "WEAPON_MICROSMG"),
			new ("冲锋枪", "WEAPON_SMG"),
			new ("突击冲锋枪", "WEAPON_ASSAULTSMG"),
			new ("突击步枪", "WEAPON_ASSAULTRIFLE"),
			new ("卡宾步枪", "WEAPON_CARBINERIFLE"),
			new ("高级步枪", "WEAPON_ADVANCEDRIFLE"),
			new ("机枪", "WEAPON_MG"),
			new ("战斗机枪", "WEAPON_COMBATMG"),
			new ("泵动式霰弹枪", "WEAPON_PUMPSHOTGUN"),
			new ("短管霰弹枪", "WEAPON_SAWNOFFSHOTGUN"),
			new ("突击霰弹枪", "WEAPON_ASSAULTSHOTGUN"),
			new ("无托式霰弹枪", "WEAPON_BULLPUPSHOTGUN"),
			new ("电击枪", "WEAPON_STUNGUN"),
			new ("狙击步枪", "WEAPON_SNIPERRIFLE"),
			new ("重型狙击步枪", "WEAPON_HEAVYSNIPER"),
			new ("遥控式狙击步枪", "WEAPON_REMOTESNIPER"),
			new ("榴弹发射器", "WEAPON_GRENADELAUNCHER"),
			new ("催泪瓦斯发射器", "WEAPON_GRENADELAUNCHER_SMOKE"),
			new ("火箭炮", "WEAPON_RPG"),
			new ("火箭炮", "WEAPON_STINGER"),
			new ("火神机枪", "WEAPON_MINIGUN"),
			new ("手榴弹", "WEAPON_GRENADE"),
			new ("黏弹", "WEAPON_STICKYBOMB"),
			new ("催泪瓦斯", "WEAPON_SMOKEGRENADE"),
			new ("毒气弹", "WEAPON_BZGAS"),
			new ("汽油弹", "WEAPON_MOLOTOV"),
			new ("灭火器", "WEAPON_FIREEXTINGUISHER"),
			new ("汽油桶", "WEAPON_PETROLCAN"),
			new ("夜视镜", "GADGET_NIGHTVISION"),
			new ("降落伞", "GADGET_PARACHUTE"),
			new ("球", "WEAPON_BALL"),
			new ("信号弹", "WEAPON_FLARE"),
			new ("坦克炮", "VEHICLE_WEAPON_TANK"),
			new ("导弹", "VEHICLE_WEAPON_SPACE_ROCKET"),
			new ("导弹", "VEHICLE_WEAPON_PLANE_ROCKET"),
			new ("激光", "VEHICLE_WEAPON_PLAYER_LASER"),
			new ("机枪", "VEHICLE_WEAPON_PLAYER_BULLET"),
			new ("机枪", "VEHICLE_WEAPON_PLAYER_BUZZARD"),
			new ("机枪", "VEHICLE_WEAPON_PLAYER_HUNTER"),
			new ("大炮", "VEHICLE_WEAPON_PLAYER_LAZER"),
			new ("激光", "VEHICLE_WEAPON_ENEMY_LASER"),
			new ("手榴弹", "WEAPON_BIRD_CRAP"),
			new ("酒瓶", "WEAPON_BOTTLE"),
			new ("劣质手枪", "WEAPON_SNSPISTOL"),
			new ("重型手枪", "WEAPON_HEAVYPISTOL"),
			new ("无托式步枪", "WEAPON_BULLPUPRIFLE"),
			new ("特制卡宾枪", "WEAPON_SPECIALCARBINE"),
			new ("Mk2劣质手枪", "WEAPON_SNSPISTOL_MK2"),
			new ("Mk2射手步枪", "WEAPON_MARKSMANRIFLE_MK2"),
			new ("Mk2泵动式霰弹枪", "WEAPON_PUMPSHOTGUN_MK2"),
			new ("Mk2无托式步枪", "WEAPON_BULLPUPRIFLE_MK2"),
			new ("MK2特制卡宾步枪", "WEAPON_SPECIALCARBINE_MK2"),
			new ("致幻剂包裹", "WEAPON_ACIDPACKAGE"),
			new ("机枪", "WEAPON_ARENA_MACHINE_GUN"),
			new ("大炮", "WEAPON_ARENA_HOMING_MISSILE"),
			new ("拐杖糖", "WEAPON_CANDYCANE"),
			new ("WM29手枪", "WEAPON_PISTOLXM3"),
			new ("电磁步枪", "WEAPON_RAILGUNXM3"),
			new ("雪球", "WEAPON_SNOWBALL"),
			new ("双动式左轮手枪", "WEAPON_DOUBLEACTION"),
			new ("制导火箭发射器", "WEAPON_HOMINGLAUNCHER"),
			new ("原子能枪", "WEAPON_RAYPISTOL"),
			new ("邪恶冥王", "WEAPON_RAYCARBINE"),
			new ("寡妇制造者", "WEAPON_RAYMINIGUN"),
			new ("Mk2重型左轮手枪", "WEAPON_REVOLVER_MK2"),
			new ("感应地雷", "WEAPON_PROXMINE"),
			new ("古森柏冲锋枪", "WEAPON_GUSENBERG"),
			new ("古董骑兵匕首", "WEAPON_DAGGER"),
			new ("老式手枪", "WEAPON_VINTAGEPISTOL"),
			new ("烟花发射器", "WEAPON_FIREWORK"),
			new ("老式火枪", "WEAPON_MUSKET"),
			new ("电磁步枪", "WEAPON_RAILGUN"),
			new ("手斧", "WEAPON_HATCHET"),
			new ("射手步枪", "WEAPON_MARKSMANRIFLE"),
			new ("重型霰弹枪", "WEAPON_HEAVYSHOTGUN"),
			new ("小刀", "WEAPON_GARBAGEBAG"),
			new ("军用步枪", "WEAPON_MILITARYRIFLE"),
			new ("佩里科手枪", "WEAPON_GADGETPISTOL"),
			new ("小刀", "WEAPON_HANDCUFFS"),
			new ("陶瓷手枪", "WEAPON_CERAMICPISTOL"),
			new ("危害性汽油桶", "WEAPON_HAZARDCAN"),
			new ("电击枪", "WEAPON_TRANQUILIZER"),
			new ("战斗霰弹枪", "WEAPON_COMBATSHOTGUN"),
			new ("海军左轮手枪", "WEAPON_NAVYREVOLVER"),
			new ("大炮", "VEHICLE_WEAPON_PLAYER_SAVAGE"),
			new ("机枪", "VEHICLE_WEAPON_NOSE_TURRET_VALKYRIE"),
			new ("机枪", "VEHICLE_WEAPON_TURRET_VALKYRIE"),
			new ("机枪", "VEHICLE_WEAPON_TURRET_TECHNICAL"),
			new ("信号枪", "WEAPON_FLAREGUN"),
			new ("机枪", "VEHICLE_WEAPON_TURRET_INSURGENT"),
			new ("手指虎", "WEAPON_KNUCKLE"),
			new ("射手手枪", "WEAPON_MARKSMANPISTOL"),
			new ("作战自卫冲锋枪", "WEAPON_COMBATPDW"),
			new ("双管霰弹枪", "WEAPON_DBSHOTGUN"),
			new ("开山刀", "WEAPON_MACHETE"),
			new ("冲锋手枪", "WEAPON_MACHINEPISTOL"),
			new ("紧凑型步枪", "WEAPON_COMPACTRIFLE"),
			new ("手电筒", "WEAPON_FLASHLIGHT"),
			new ("大炮", "WEAPON_AIR_DEFENCE_GUN"),
			new ("机枪", "VEHICLE_WEAPON_TURRET_LIMO"),
			new ("弹簧刀", "WEAPON_SWITCHBLADE"),
			new ("重型左轮手枪", "WEAPON_REVOLVER"),
			new ("机枪", "VEHICLE_WEAPON_TURRET_BOXVILLE"),
			new ("机枪", "VEHICLE_WEAPON_RUINER_BULLET"),
			new ("导弹", "VEHICLE_WEAPON_RUINER_ROCKET"),
			new ("机枪", "VEHICLE_WEAPON_CANNON_BLAZER"),
			new ("战斗斧", "WEAPON_BATTLEAXE"),
			new ("冲锋霰弹枪", "WEAPON_AUTOSHOTGUN"),
			new ("迷你冲锋枪", "WEAPON_MINISMG"),
			new ("台球杆", "WEAPON_POOLCUE"),
			new ("管钳扳手", "WEAPON_WRENCH"),
			new ("紧凑型榴弹发射器", "WEAPON_COMPACTLAUNCHER"),
			new ("土制炸弹", "WEAPON_PIPEBOMB"),
			new ("Mk2战斗机枪", "WEAPON_COMBATMG_MK2"),
			new ("Mk2突击步枪", "WEAPON_ASSAULTRIFLE_MK2"),
			new ("Mk2冲锋枪", "WEAPON_SMG_MK2"),
			new ("Mk2卡宾步枪", "WEAPON_CARBINERIFLE_MK2"),
			new ("Mk2手枪", "WEAPON_PISTOL_MK2"),
			new ("Mk2重型狙击步枪", "WEAPON_HEAVYSNIPER_MK2"),
			new ("石斧", "WEAPON_STONE_HATCHET"),
			new ("制式卡宾步枪", "WEAPON_TACTICALRIFLE"),
			new ("精确步枪", "WEAPON_PRECISIONRIFLE"),
			new ("重型步枪", "WEAPON_HEAVYRIFLE"),
			new ("肥料桶", "WEAPON_FERTILIZERCAN"),
			new ("紧凑型电磁脉冲发射器", "WEAPON_EMPLAUNCHER"),
			new ("电击枪", "WEAPON_STUNGUN_MP"),
			new ("战术冲锋枪", "WEAPON_TECPISTOL"),
			new ("雪球发射器", "WEAPON_SNOWLAUNCHER"),
			new ("骇入设备", "WEAPON_HACKINGDEVICE"),
			new ("战斗步枪", "WEAPON_BATTLERIFLE"),
			new ("电击棒", "WEAPON_STUNROD"),
			new ("毒枭金步枪", "WEAPON_STRICKLER"),
		];

		public static readonly Dictionary<string, List<ItemInfo>> WeaponComponents = new(){
			{ "WEAPON_KNIFE", new List<ItemInfo> { new ("眼睛", "COMPONENT_KNIFE_VARMOD_XM3"), new ("飞溅", "COMPONENT_KNIFE_VARMOD_XM3_01"), new ("烈焰", "COMPONENT_KNIFE_VARMOD_XM3_02"), new ("闪电", "COMPONENT_KNIFE_VARMOD_XM3_03"), new ("摇头丸", "COMPONENT_KNIFE_VARMOD_XM3_04"), new ("蛇皮", "COMPONENT_KNIFE_VARMOD_XM3_05"), new ("自由卢查", "COMPONENT_KNIFE_VARMOD_XM3_06"), new ("幻境", "COMPONENT_KNIFE_VARMOD_XM3_07"), new ("龙舌你丫", "COMPONENT_KNIFE_VARMOD_XM3_08"), new ("橙色珍味", "COMPONENT_KNIFE_VARMOD_XM3_09") } },
			{ "WEAPON_BAT", new List<ItemInfo> { new ("潮笑王", "COMPONENT_BAT_VARMOD_XM3"), new ("飞溅", "COMPONENT_BAT_VARMOD_XM3_01"), new ("弹孔", "COMPONENT_BAT_VARMOD_XM3_02"), new ("吃得饱汉堡", "COMPONENT_BAT_VARMOD_XM3_03"), new ("当当钟", "COMPONENT_BAT_VARMOD_XM3_04"), new ("致命侵袭", "COMPONENT_BAT_VARMOD_XM3_05"), new ("自由卢查", "COMPONENT_BAT_VARMOD_XM3_06"), new ("幻境", "COMPONENT_BAT_VARMOD_XM3_07"), new ("扎染", "COMPONENT_BAT_VARMOD_XM3_08"), new ("墙壁", "COMPONENT_BAT_VARMOD_XM3_09") } },
			{ "WEAPON_PISTOL", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_PISTOL_CLIP_01"), new ("扩充弹匣", "COMPONENT_PISTOL_CLIP_02"), new ("手电筒", "COMPONENT_AT_PI_FLSH"), new ("消音器", "COMPONENT_AT_PI_SUPP_02"), new ("尤素福·阿米尔奢华涂饰", "COMPONENT_PISTOL_VARMOD_LUXE"), new ("Mk2", "COMPONENT_GUNRUN_MK2_UPGRADE") } },
			{ "WEAPON_COMBATPISTOL", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_COMBATPISTOL_CLIP_01"), new ("扩充弹匣", "COMPONENT_COMBATPISTOL_CLIP_02"), new ("手电筒", "COMPONENT_AT_PI_FLSH"), new ("消音器", "COMPONENT_AT_PI_SUPP"), new ("尤素福·阿米尔奢华涂饰", "COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER") } },
			{ "WEAPON_APPISTOL", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_APPISTOL_CLIP_01"), new ("扩充弹匣", "COMPONENT_APPISTOL_CLIP_02"), new ("手电筒", "COMPONENT_AT_PI_FLSH"), new ("消音器", "COMPONENT_AT_PI_SUPP"), new ("镀金枪械金属涂饰", "COMPONENT_APPISTOL_VARMOD_LUXE"), new ("录音A涂饰", "COMPONENT_APPISTOL_VARMOD_SECURITY") } },
			{ "WEAPON_PISTOL50", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_PISTOL50_CLIP_01"), new ("扩充弹匣", "COMPONENT_PISTOL50_CLIP_02"), new ("手电筒", "COMPONENT_AT_PI_FLSH"), new ("消音器", "COMPONENT_AT_AR_SUPP_02"), new ("铂金 珍珠豪华涂饰", "COMPONENT_PISTOL50_VARMOD_LUXE") } },
			{ "WEAPON_MICROSMG", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_MICROSMG_CLIP_01"), new ("扩充弹匣", "COMPONENT_MICROSMG_CLIP_02"), new ("手电筒", "COMPONENT_AT_PI_FLSH"), new ("瞄准镜", "COMPONENT_AT_SCOPE_MACRO"), new ("消音器", "COMPONENT_AT_AR_SUPP_02"), new ("尤素福·阿米尔奢华涂饰", "COMPONENT_MICROSMG_VARMOD_LUXE"), new ("有机坊涂饰", "COMPONENT_MICROSMG_VARMOD_SECURITY"), new ("雕哥迷彩", "COMPONENT_MICROSMG_VARMOD_XM3") } },
			{ "WEAPON_SMG", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_SMG_CLIP_01"), new ("扩充弹匣", "COMPONENT_SMG_CLIP_02"), new ("鼓式弹匣", "COMPONENT_SMG_CLIP_03"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("瞄准镜", "COMPONENT_AT_SCOPE_MACRO_02"), new ("消音器", "COMPONENT_AT_PI_SUPP"), new ("尤素福·阿米尔奢华涂饰", "COMPONENT_SMG_VARMOD_LUXE"), new ("Mk2", "COMPONENT_GUNRUN_MK2_UPGRADE") } },
			{ "WEAPON_ASSAULTSMG", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_ASSAULTSMG_CLIP_01"), new ("扩充弹匣", "COMPONENT_ASSAULTSMG_CLIP_02"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("瞄准镜", "COMPONENT_AT_SCOPE_MACRO"), new ("消音器", "COMPONENT_AT_AR_SUPP_02"), new ("尤素福·阿米尔奢华涂饰", "COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER") } },
			{ "WEAPON_ASSAULTRIFLE", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_ASSAULTRIFLE_CLIP_01"), new ("扩充弹匣", "COMPONENT_ASSAULTRIFLE_CLIP_02"), new ("鼓式弹匣", "COMPONENT_ASSAULTRIFLE_CLIP_03"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("瞄准镜", "COMPONENT_AT_SCOPE_MACRO"), new ("消音器", "COMPONENT_AT_AR_SUPP_02"), new ("握把", "COMPONENT_AT_AR_AFGRIP"), new ("尤素福·阿米尔奢华涂饰", "COMPONENT_ASSAULTRIFLE_VARMOD_LUXE"), new ("Mk2", "COMPONENT_GUNRUN_MK2_UPGRADE") } },
			{ "WEAPON_CARBINERIFLE", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_CARBINERIFLE_CLIP_01"), new ("扩充弹匣", "COMPONENT_CARBINERIFLE_CLIP_02"), new ("盒式弹匣", "COMPONENT_CARBINERIFLE_CLIP_03"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("瞄准镜", "COMPONENT_AT_SCOPE_MEDIUM"), new ("消音器", "COMPONENT_AT_AR_SUPP"), new ("握把", "COMPONENT_AT_AR_AFGRIP"), new ("尤素福·阿米尔奢华涂饰", "COMPONENT_CARBINERIFLE_VARMOD_LUXE"), new ("Mk2", "COMPONENT_GUNRUN_MK2_UPGRADE") } },
			{ "WEAPON_ADVANCEDRIFLE", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_ADVANCEDRIFLE_CLIP_01"), new ("扩充弹匣", "COMPONENT_ADVANCEDRIFLE_CLIP_02"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("瞄准镜", "COMPONENT_AT_SCOPE_SMALL"), new ("消音器", "COMPONENT_AT_AR_SUPP"), new ("镀金枪械金属涂饰", "COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE") } },
			{ "WEAPON_MG", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_MG_CLIP_01"), new ("扩充弹匣", "COMPONENT_MG_CLIP_02"), new ("瞄准镜", "COMPONENT_AT_SCOPE_SMALL_02"), new ("尤素福·阿米尔奢华涂饰", "COMPONENT_MG_VARMOD_LOWRIDER") } },
			{ "WEAPON_COMBATMG", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_COMBATMG_CLIP_01"), new ("扩充弹匣", "COMPONENT_COMBATMG_CLIP_02"), new ("瞄准镜", "COMPONENT_AT_SCOPE_MEDIUM"), new ("握把", "COMPONENT_AT_AR_AFGRIP"), new ("蚀 刻枪械金属涂饰", "COMPONENT_COMBATMG_VARMOD_LOWRIDER"), new ("Mk2", "COMPONENT_GUNRUN_MK2_UPGRADE") } },
			{ "WEAPON_PUMPSHOTGUN", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_PUMPSHOTGUN_CLIP_01"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("消音器", "COMPONENT_AT_SR_SUPP"), new ("尤素福·阿米尔奢华涂饰", "COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER"), new ("Mk2", "COMPONENT_GUNRUN_MK2_UPGRADE"), new ("骸骨涂饰", "COMPONENT_PUMPSHOTGUN_VARMOD_SECURITY"), new ("雕哥迷彩", "COMPONENT_PUMPSHOTGUN_VARMOD_XM3") } },
			{ "WEAPON_SAWNOFFSHOTGUN", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_SAWNOFFSHOTGUN_CLIP_01"), new ("镀金枪械金属涂饰", "COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE") } },
			{ "WEAPON_ASSAULTSHOTGUN", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_ASSAULTSHOTGUN_CLIP_01"), new ("扩充弹匣", "COMPONENT_ASSAULTSHOTGUN_CLIP_02"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("消音器", "COMPONENT_AT_AR_SUPP"), new ("握把", "COMPONENT_AT_AR_AFGRIP") } },
			{ "WEAPON_BULLPUPSHOTGUN", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_BULLPUPSHOTGUN_CLIP_01"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("消音器", "COMPONENT_AT_AR_SUPP_02"), new ("握把", "COMPONENT_AT_AR_AFGRIP") } },
			{ "WEAPON_SNIPERRIFLE", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_SNIPERRIFLE_CLIP_01"), new ("消音器", "COMPONENT_AT_AR_SUPP_02"), new ("瞄准镜", "COMPONENT_AT_SCOPE_LARGE"), new ("高级瞄准镜", "COMPONENT_AT_SCOPE_MAX"), new ("蚀刻木质枪柄涂饰", "COMPONENT_SNIPERRIFLE_VARMOD_LUXE") } },
			{ "WEAPON_HEAVYSNIPER", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_HEAVYSNIPER_CLIP_01"), new ("瞄准镜", "COMPONENT_AT_SCOPE_LARGE"), new ("高级瞄准镜", "COMPONENT_AT_SCOPE_MAX"), new ("Mk2", "COMPONENT_GUNRUN_MK2_UPGRADE") } },
			{ "WEAPON_GRENADELAUNCHER", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_GRENADELAUNCHER_CLIP_01"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("握把", "COMPONENT_AT_AR_AFGRIP"), new ("瞄准镜", "COMPONENT_AT_SCOPE_SMALL") } },
			{ "WEAPON_GRENADELAUNCHER_SMOKE", new List<ItemInfo> { new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("握把", "COMPONENT_AT_AR_AFGRIP"), new ("瞄准镜", "COMPONENT_AT_SCOPE_SMALL") } },
			{ "WEAPON_RPG", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_RPG_CLIP_01") } },
			{ "WEAPON_PASSENGER_ROCKET", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_RPG_CLIP_01") } },
			{ "WEAPON_AIRSTRIKE_ROCKET", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_RPG_CLIP_01") } },
			{ "WEAPON_STINGER", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_RPG_CLIP_01") } },
			{ "WEAPON_MINIGUN", new List<ItemInfo> { new ("扩充弹匣", "COMPONENT_MINIGUN_CLIP_01") } },
			{ "OBJECT", new List<ItemInfo> { new ("手电筒", "POLICE_TORCH_FLASHLIGHT") } },
			{ "WEAPON_VEHICLE_ROCKET", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_RPG_CLIP_01") } },
			{ "WEAPON_SNSPISTOL", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_SNSPISTOL_CLIP_01"), new ("扩充弹匣", "COMPONENT_SNSPISTOL_CLIP_02"), new ("蚀刻木质枪柄涂饰", "COMPONENT_SNSPISTOL_VARMOD_LOWRIDER"), new ("Mk2", "COMPONENT_GUNRUN_MK2_UPGRADE") } },
			{ "WEAPON_HEAVYPISTOL", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_HEAVYPISTOL_CLIP_01"), new ("扩充弹匣", "COMPONENT_HEAVYPISTOL_CLIP_02"), new ("手电筒", "COMPONENT_AT_PI_FLSH"), new ("消音器", "COMPONENT_AT_PI_SUPP"), new ("蚀刻木质枪柄涂饰", "COMPONENT_HEAVYPISTOL_VARMOD_LUXE") } },
			{ "WEAPON_BULLPUPRIFLE", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_BULLPUPRIFLE_CLIP_01"), new ("扩充弹匣", "COMPONENT_BULLPUPRIFLE_CLIP_02"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("瞄准镜", "COMPONENT_AT_SCOPE_SMALL"), new ("消音器", "COMPONENT_AT_AR_SUPP"), new ("握把", "COMPONENT_AT_AR_AFGRIP"), new ("镀金枪械金属涂饰", "COMPONENT_BULLPUPRIFLE_VARMOD_LOW"), new ("Mk2", "COMPONENT_GUNRUN_MK2_UPGRADE") } },
			{ "WEAPON_SPECIALCARBINE", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_SPECIALCARBINE_CLIP_01"), new ("扩充弹匣", "COMPONENT_SPECIALCARBINE_CLIP_02"), new ("鼓式弹匣", "COMPONENT_SPECIALCARBINE_CLIP_03"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("瞄准镜", "COMPONENT_AT_SCOPE_MEDIUM"), new ("消音器", "COMPONENT_AT_AR_SUPP_02"), new ("握把", "COMPONENT_AT_AR_AFGRIP"), new ("蚀刻枪械金属涂饰", "COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER"), new ("Mk2", "COMPONENT_GUNRUN_MK2_UPGRADE") } },
			{ "WEAPON_SNSPISTOL_MK2", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_SNSPISTOL_MK2_CLIP_01"), new ("扩充弹匣", "COMPONENT_SNSPISTOL_MK2_CLIP_02"), new ("曳光子弹", "COMPONENT_SNSPISTOL_MK2_CLIP_TRACER"), new ("燃烧子弹", "COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY"), new ("中空子弹", "COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT"), new ("全金属外壳子弹", "COMPONENT_SNSPISTOL_MK2_CLIP_FMJ"), new ("手电筒", "COMPONENT_AT_PI_FLSH_03"), new ("固定瞄准镜", "COMPONENT_AT_PI_RAIL_02"), new ("消音器", "COMPONENT_AT_PI_SUPP_02"), new ("补偿器", "COMPONENT_AT_PI_COMP_02") } },
			{ "WEAPON_MARKSMANRIFLE_MK2", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_01"), new ("扩充弹匣", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_02"), new ("穿甲子弹", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING"), new ("全金属外壳子弹", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ"), new ("燃烧子弹", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY"), new ("曳光子弹", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("全息瞄准镜", "COMPONENT_AT_SIGHTS"), new ("大型瞄准镜", "COMPONENT_AT_SCOPE_MEDIUM_MK2"), new ("缩放瞄准镜", "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2"), new ("消音器", "COMPONENT_AT_AR_SUPP"), new ("枪口制动 器", "COMPONENT_AT_MUZZLE_01"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_02"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_03"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_04"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_05"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_06"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_07"), new ("握把", "COMPONENT_AT_AR_AFGRIP_02"), new ("默认枪管", "COMPONENT_AT_MRFL_BARREL_01"), new ("重型枪管", "COMPONENT_AT_MRFL_BARREL_02") } },
			{ "WEAPON_PUMPSHOTGUN_MK2", new List<ItemInfo> { new ("默认弹药", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_01"), new ("钢制铅弹", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING"), new ("爆破子弹", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE"), new ("箭型弹", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT"), new ("龙息弹", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY"), new ("全息瞄准镜", "COMPONENT_AT_SIGHTS"), new ("小型瞄准镜", "COMPONENT_AT_SCOPE_MACRO_MK2"), new (" 中型瞄准镜", "COMPONENT_AT_SCOPE_SMALL_MK2"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("消音器", "COMPONENT_AT_SR_SUPP_03"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_08") } },
			{ "WEAPON_BULLPUPRIFLE_MK2", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_01"), new ("扩充弹匣", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_02"), new ("曳光子弹", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER"), new ("燃烧子弹", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY"), new ("穿甲子弹", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING"), new ("全金属外壳子弹", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("全息瞄准镜", "COMPONENT_AT_SIGHTS"), new ("小型瞄准镜", "COMPONENT_AT_SCOPE_MACRO_02_MK2"), new ("中型瞄 准镜", "COMPONENT_AT_SCOPE_SMALL_MK2"), new ("默认枪管", "COMPONENT_AT_BP_BARREL_01"), new ("重型枪管", "COMPONENT_AT_BP_BARREL_02"), new ("消音器", "COMPONENT_AT_AR_SUPP"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_01"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_02"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_03"), new ("枪口制 动器", "COMPONENT_AT_MUZZLE_04"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_05"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_06"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_07"), new ("握把", "COMPONENT_AT_AR_AFGRIP_02") } },
			{ "WEAPON_SPECIALCARBINE_MK2", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_SPECIALCARBINE_MK2_CLIP_01"), new ("扩充弹匣", "COMPONENT_SPECIALCARBINE_MK2_CLIP_02"), new ("曳光子弹", "COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER"), new (" 燃烧子弹", "COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY"), new ("穿甲子弹", "COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING"), new ("全金属外壳子弹", "COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("全息瞄准镜", "COMPONENT_AT_SIGHTS"), new ("小型瞄准镜", "COMPONENT_AT_SCOPE_MACRO_MK2"), new ("大型瞄准镜", "COMPONENT_AT_SCOPE_MEDIUM_MK2"), new ("消音器", "COMPONENT_AT_AR_SUPP_02"), new ("枪口制动 器", "COMPONENT_AT_MUZZLE_01"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_02"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_03"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_04"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_05"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_06"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_07"), new ("握把", "COMPONENT_AT_AR_AFGRIP_02"), new ("默认枪管", "COMPONENT_AT_SC_BARREL_01"), new ("重型枪管", "COMPONENT_AT_SC_BARREL_02") } },
			{ "WEAPON_PISTOLXM3", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_PISTOLXM3_CLIP_01"), new ("消音器", "COMPONENT_PISTOLXM3_SUPP") } },
			{ "WEAPON_RAILGUNXM3", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_RAILGUNXM3_CLIP_01") } },
			{ "WEAPON_DOUBLEACTION", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_DOUBLEACTION_CLIP_01") } },
			{ "WEAPON_HOMINGLAUNCHER", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_HOMINGLAUNCHER_CLIP_01") } },
			{ "WEAPON_RAYPISTOL", new List<ItemInfo> { new ("节庆色调", "COMPONENT_RAYPISTOL_VARMOD_XMAS18") } },
			{ "WEAPON_RAYMINIGUN", new List<ItemInfo> { new ("扩充弹匣", "COMPONENT_MINIGUN_CLIP_01") } },
			{ "WEAPON_REVOLVER_MK2", new List<ItemInfo> { new ("默认子弹", "COMPONENT_REVOLVER_MK2_CLIP_01"), new ("全金属外壳子弹", "COMPONENT_REVOLVER_MK2_CLIP_FMJ"), new ("中空子弹", "COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT"), new ("燃烧子弹", "COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY"), new ("曳光子弹", "COMPONENT_REVOLVER_MK2_CLIP_TRACER"), new ("全息瞄 准镜", "COMPONENT_AT_SIGHTS"), new ("小型瞄准镜", "COMPONENT_AT_SCOPE_MACRO_MK2"), new ("手电筒", "COMPONENT_AT_PI_FLSH"), new ("补偿器", "COMPONENT_AT_PI_COMP_03") } },
			{ "WEAPON_GUSENBERG", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_GUSENBERG_CLIP_01"), new ("扩充弹匣", "COMPONENT_GUSENBERG_CLIP_02") } },
			{ "WEAPON_VINTAGEPISTOL", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_VINTAGEPISTOL_CLIP_01"), new ("扩充弹匣", "COMPONENT_VINTAGEPISTOL_CLIP_02"), new ("消音器", "COMPONENT_AT_PI_SUPP") } },
			{ "WEAPON_FIREWORK", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_FIREWORK_CLIP_01") } },
			{ "WEAPON_MUSKET", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_MUSKET_CLIP_01") } },
			{ "WEAPON_RAILGUN", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_RAILGUN_CLIP_01") } },
			{ "WEAPON_MARKSMANRIFLE", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_MARKSMANRIFLE_CLIP_01"), new ("扩充弹匣", "COMPONENT_MARKSMANRIFLE_CLIP_02"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("瞄准镜", "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM"), new ("消音器", "COMPONENT_AT_AR_SUPP"), new ("握把", "COMPONENT_AT_AR_AFGRIP"), new ("尤素福· 阿米尔奢华涂饰", "COMPONENT_MARKSMANRIFLE_VARMOD_LUXE"), new ("Mk2", "COMPONENT_GUNRUN_MK2_UPGRADE") } },
			{ "WEAPON_HEAVYSHOTGUN", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_HEAVYSHOTGUN_CLIP_01"), new ("扩充弹匣", "COMPONENT_HEAVYSHOTGUN_CLIP_02"), new ("鼓式弹匣", "COMPONENT_HEAVYSHOTGUN_CLIP_03"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("消音器", "COMPONENT_AT_AR_SUPP_02"), new ("握把", "COMPONENT_AT_AR_AFGRIP") } },
			{ "WEAPON_MILITARYRIFLE", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_MILITARYRIFLE_CLIP_01"), new ("扩充弹匣", "COMPONENT_MILITARYRIFLE_CLIP_02"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("机械瞄具", "COMPONENT_MILITARYRIFLE_SIGHT_01"), new ("瞄准镜", "COMPONENT_AT_SCOPE_SMALL"), new ("消音器", "COMPONENT_AT_AR_SUPP") } },
			{ "WEAPON_GADGETPISTOL", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_GADGETPISTOL_CLIP_01") } },
			{ "WEAPON_CERAMICPISTOL", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_CERAMICPISTOL_CLIP_01"), new ("扩充弹匣", "COMPONENT_CERAMICPISTOL_CLIP_02"), new ("消音器", "COMPONENT_CERAMICPISTOL_SUPP") } },
			{ "WEAPON_COMBATSHOTGUN", new List<ItemInfo> { new ("默认弹药", "COMPONENT_COMBATSHOTGUN_CLIP_01"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("消音器", "COMPONENT_AT_AR_SUPP") } },
			{ "WEAPON_NAVYREVOLVER", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_NAVYREVOLVER_CLIP_01") } },
			{ "WEAPON_FLAREGUN", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_FLAREGUN_CLIP_01") } },
			{ "WEAPON_KNUCKLE", new List<ItemInfo> { new ("手指虎", "COMPONENT_KNUCKLE_VARMOD_BASE"), new ("皮条客", "COMPONENT_KNUCKLE_VARMOD_PIMP"), new ("巴勒帮", "COMPONENT_KNUCKLE_VARMOD_BALLAS"), new ("江湖骗子", "COMPONENT_KNUCKLE_VARMOD_DOLLAR"), new ("摇滚乐", "COMPONENT_KNUCKLE_VARMOD_DIAMOND"), new ("痛恨者", "COMPONENT_KNUCKLE_VARMOD_HATE"), new ("情人", "COMPONENT_KNUCKLE_VARMOD_LOVE"), new ("赌徒", "COMPONENT_KNUCKLE_VARMOD_PLAYER"), new ("城堡之王", "COMPONENT_KNUCKLE_VARMOD_KING"), new ("维戈斯帮", "COMPONENT_KNUCKLE_VARMOD_VAGOS") } },
			{ "WEAPON_MARKSMANPISTOL", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_MARKSMANPISTOL_CLIP_01") } },
			{ "WEAPON_COMBATPDW", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_COMBATPDW_CLIP_01"), new ("扩充弹匣", "COMPONENT_COMBATPDW_CLIP_02"), new ("鼓式弹匣", "COMPONENT_COMBATPDW_CLIP_03"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("握把", "COMPONENT_AT_AR_AFGRIP"), new ("瞄准镜", "COMPONENT_AT_SCOPE_SMALL") } },
			{ "WEAPON_DBSHOTGUN", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_DBSHOTGUN_CLIP_01") } },
			{ "WEAPON_MACHINEPISTOL", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_MACHINEPISTOL_CLIP_01"), new ("扩充弹匣", "COMPONENT_MACHINEPISTOL_CLIP_02"), new ("鼓式弹匣", "COMPONENT_MACHINEPISTOL_CLIP_03"), new ("消音器", "COMPONENT_AT_PI_SUPP") } },
			{ "WEAPON_COMPACTRIFLE", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_COMPACTRIFLE_CLIP_01"), new ("扩充弹匣", "COMPONENT_COMPACTRIFLE_CLIP_02"), new ("鼓式弹匣", "COMPONENT_COMPACTRIFLE_CLIP_03") } },
			{ "WEAPON_FLASHLIGHT", new List<ItemInfo> { new ("手电筒", "COMPONENT_FLASHLIGHT_LIGHT") } },
			{ "WEAPON_SWITCHBLADE", new List<ItemInfo> { new ("默认刀柄", "COMPONENT_SWITCHBLADE_VARMOD_BASE"), new ("VIP样式", "COMPONENT_SWITCHBLADE_VARMOD_VAR1"), new ("保镖样式", "COMPONENT_SWITCHBLADE_VARMOD_VAR2") } },
			{ "WEAPON_REVOLVER", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_REVOLVER_CLIP_01"), new ("VIP样式", "COMPONENT_REVOLVER_VARMOD_BOSS"), new ("保镖样式", "COMPONENT_REVOLVER_VARMOD_GOON"), new ("Mk2", "COMPONENT_GUNRUN_MK2_UPGRADE") } },
			{ "WEAPON_AUTOSHOTGUN", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_AUTOSHOTGUN_CLIP_01") } },
			{ "WEAPON_MINISMG", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_MINISMG_CLIP_01"), new ("扩充弹匣", "COMPONENT_MINISMG_CLIP_02") } },
			{ "WEAPON_COMPACTLAUNCHER", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_COMPACTLAUNCHER_CLIP_01") } },
			{ "WEAPON_COMBATMG_MK2", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_COMBATMG_MK2_CLIP_01"), new ("扩充弹匣", "COMPONENT_COMBATMG_MK2_CLIP_02"), new ("穿甲子弹", "COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING"), new ("全金属外壳子弹", "COMPONENT_COMBATMG_MK2_CLIP_FMJ"), new ("燃烧子弹", "COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY"), new ("曳光子弹", "COMPONENT_COMBATMG_MK2_CLIP_TRACER"), new ("全息瞄准镜", "COMPONENT_AT_SIGHTS"), new ("中型瞄准镜", "COMPONENT_AT_SCOPE_SMALL_MK2"), new ("大型瞄准镜", "COMPONENT_AT_SCOPE_MEDIUM_MK2"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_01"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_02"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_03"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_04"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_05"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_06"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_07"), new ("握把", "COMPONENT_AT_AR_AFGRIP_02"), new ("默认枪管", "COMPONENT_AT_MG_BARREL_01"), new ("重型枪管", "COMPONENT_AT_MG_BARREL_02") } },
			{ "WEAPON_ASSAULTRIFLE_MK2", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_01"), new ("扩充弹匣", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02"), new ("穿甲子弹", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING"), new ("全金属外壳子弹", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ"), new ("燃烧子弹", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY"), new ("曳光子弹", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("全息瞄准镜", "COMPONENT_AT_SIGHTS"), new ("小型瞄准镜", "COMPONENT_AT_SCOPE_MACRO_MK2"), new ("大型瞄准镜", "COMPONENT_AT_SCOPE_MEDIUM_MK2"), new ("消音器", "COMPONENT_AT_AR_SUPP_02"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_01"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_02"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_03"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_04"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_05"), new ("枪口制动 器", "COMPONENT_AT_MUZZLE_06"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_07"), new ("握把", "COMPONENT_AT_AR_AFGRIP_02"), new ("默认枪管", "COMPONENT_AT_AR_BARREL_01"), new ("重型枪管", "COMPONENT_AT_AR_BARREL_02") } },
			{ "WEAPON_SMG_MK2", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_SMG_MK2_CLIP_01"), new ("扩充弹匣", "COMPONENT_SMG_MK2_CLIP_02"), new ("全金属外壳子弹", "COMPONENT_SMG_MK2_CLIP_FMJ"), new ("中空子弹", "COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT"), new ("燃烧子弹", "COMPONENT_SMG_MK2_CLIP_INCENDIARY"), new ("曳光子弹", "COMPONENT_SMG_MK2_CLIP_TRACER"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("全息瞄准镜", "COMPONENT_AT_SIGHTS_SMG"), new ("小型瞄准镜", "COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2"), new ("中型瞄准镜", "COMPONENT_AT_SCOPE_SMALL_SMG_MK2"), new ("消 音器", "COMPONENT_AT_PI_SUPP"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_01"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_02"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_03"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_04"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_05"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_06"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_07"), new ("默认枪管", "COMPONENT_AT_SB_BARREL_01"), new ("重型枪管", "COMPONENT_AT_SB_BARREL_02") } },
			{ "WEAPON_CARBINERIFLE_MK2", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_CARBINERIFLE_MK2_CLIP_01"), new ("扩充弹匣", "COMPONENT_CARBINERIFLE_MK2_CLIP_02"), new ("穿甲子弹", "COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING"), new ("全金属外壳子弹", "COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ"), new ("燃烧子弹", "COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY"), new ("曳光子弹", "COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("全息瞄准镜", "COMPONENT_AT_SIGHTS"), new ("小型瞄准镜", "COMPONENT_AT_SCOPE_MACRO_MK2"), new ("大型瞄准镜", "COMPONENT_AT_SCOPE_MEDIUM_MK2"), new ("消音器", "COMPONENT_AT_AR_SUPP"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_01"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_02"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_03"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_04"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_05"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_06"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_07"), new ("握把", "COMPONENT_AT_AR_AFGRIP_02"), new ("默认枪管", "COMPONENT_AT_CR_BARREL_01"), new ("重型枪管", "COMPONENT_AT_CR_BARREL_02") } },
			{ "WEAPON_PISTOL_MK2", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_PISTOL_MK2_CLIP_01"), new ("扩充弹匣", "COMPONENT_PISTOL_MK2_CLIP_02"), new ("全金属外壳子弹", "COMPONENT_PISTOL_MK2_CLIP_FMJ"), new ("中空子弹", "COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT"), new ("燃烧子弹", "COMPONENT_PISTOL_MK2_CLIP_INCENDIARY"), new ("曳光子弹", "COMPONENT_PISTOL_MK2_CLIP_TRACER"), new ("固定瞄准镜", "COMPONENT_AT_PI_RAIL"), new ("手电筒", "COMPONENT_AT_PI_FLSH_02"), new ("消音器", "COMPONENT_AT_PI_SUPP_02"), new ("补偿器", "COMPONENT_AT_PI_COMP"), new ("节日快乐", "COMPONENT_PISTOL_MK2_VARMOD_XM3") } },
			{ "WEAPON_HEAVYSNIPER_MK2", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_HEAVYSNIPER_MK2_CLIP_01"), new ("扩充弹匣", "COMPONENT_HEAVYSNIPER_MK2_CLIP_02"), new ("穿甲子弹", "COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING"), new ("爆炸子弹", "COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE"), new ("全金属外壳子弹", "COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ"), new ("燃烧子弹", "COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY"), new ("缩放瞄准镜", "COMPONENT_AT_SCOPE_LARGE_MK2"), new ("高级瞄准镜", "COMPONENT_AT_SCOPE_MAX"), new ("夜视瞄准镜", "COMPONENT_AT_SCOPE_NV"), new ("热成像瞄准镜", "COMPONENT_AT_SCOPE_THERMAL"), new ("消音器", "COMPONENT_AT_SR_SUPP_03"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_08"), new ("枪口制动器", "COMPONENT_AT_MUZZLE_09"), new ("默认枪管", "COMPONENT_AT_SR_BARREL_01"), new ("重型枪管", "COMPONENT_AT_SR_BARREL_02") } },
			{ "WEAPON_TACTICALRIFLE", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_TACTICALRIFLE_CLIP_01"), new ("扩充弹匣", "COMPONENT_TACTICALRIFLE_CLIP_02"), new ("手电筒", "COMPONENT_AT_AR_FLSH_REH"), new ("消音器", "COMPONENT_AT_AR_SUPP_02"), new ("握把", "COMPONENT_AT_AR_AFGRIP") } },
			{ "WEAPON_PRECISIONRIFLE", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_PRECISIONRIFLE_CLIP_01") } },
			{ "WEAPON_HEAVYRIFLE", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_HEAVYRIFLE_CLIP_01"), new ("扩充弹匣", "COMPONENT_HEAVYRIFLE_CLIP_02"), new ("机械瞄具", "COMPONENT_HEAVYRIFLE_SIGHT_01"), new ("瞄准镜", "COMPONENT_AT_SCOPE_MEDIUM"), new ("手电筒", "COMPONENT_AT_AR_FLSH"), new ("消音器", "COMPONENT_AT_AR_SUPP"), new ("握把", "COMPONENT_AT_AR_AFGRIP") } },
			{ "WEAPON_EMPLAUNCHER", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_EMPLAUNCHER_CLIP_01") } },
			{ "WEAPON_TECPISTOL", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_TECPISTOL_CLIP_01"), new ("扩充弹匣", "COMPONENT_TECPISTOL_CLIP_02"), new ("消音器", "COMPONENT_AT_AR_SUPP_02"), new ("瞄准镜", "COMPONENT_AT_SCOPE_MACRO") } },
			{ "WEAPON_BATTLERIFLE", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_BATTLERIFLE_CLIP_01"), new ("扩充弹匣", "COMPONENT_BATTLERIFLE_CLIP_02"), new ("消音器", "COMPONENT_AT_AR_SUPP") } },
			{ "WEAPON_STRICKLER", new List<ItemInfo> { new ("默认弹匣", "COMPONENT_STRICKLER_CLIP_01"), new ("瞄准镜", "COMPONENT_STRICKLER_SIGHT"), new ("手电筒", "COMPONENT_STRICKLER_FLSH") } },
		};
	}
}
