export module ResourcesInfo;

export struct ItemInfo
{
public:
	constexpr ItemInfo(const char* modelID, const char* name) : ModelID(modelID), Name(name)
	{
	}

	const char* ModelID;  //游戏内资源文件名
	const char* Name; //修改器显示的名称，翻译时候改这个字段就行
};

export ItemInfo WeaponInfos[] =
{
	ItemInfo("WEAPON_PISTOL_MAUSER", "毛瑟手枪"),
	ItemInfo("WEAPON_PISTOL_M1899", "M1899"),
	ItemInfo("WEAPON_PISTOL_MAUSER_DRUNK", "米德奈特的毛瑟手枪"),
	ItemInfo("WEAPON_SHOTGUN_DOUBLEBARREL", "双管霰弹枪"),
	ItemInfo("WEAPON_SHOTGUN_SAWEDOFF", "削短型霰弹枪"),
	ItemInfo("WEAPON_SHOTGUN_SEMIAUTO", "半自动霰弹枪"),
	ItemInfo("WEAPON_SHOTGUN_REPEATING", "连发霰弹枪"),
	ItemInfo("WEAPON_SHOTGUN_PUMP", "泵动式霰弹枪"),
	ItemInfo("WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC", "稀有霰弹枪"),
	ItemInfo("WEAPON_REPEATER_CARBINE", "卡宾连发步枪"),
	ItemInfo("WEAPON_REPEATER_WINCHESTER", "蓝卡斯特连发步枪"),
	ItemInfo("WEAPON_REPEATER_HENRY", "利奇菲尔德连发步枪"),
	ItemInfo("WEAPON_RIFLE_SPRINGFIELD", "春田步枪"),
	ItemInfo("WEAPON_RIFLE_BOLTACTION", "拉栓式步枪"),
	ItemInfo("WEAPON_RIFLE_VARMINT", "捕猎步枪"),
	ItemInfo("WEAPON_SNIPERRIFLE_ROLLINGBLOCK_EXOTIC", "稀有滚轮闭锁式步枪"),
	ItemInfo("WEAPON_SNIPERRIFLE_CARCANO", "卡尔卡诺步枪"),
	ItemInfo("WEAPON_SNIPERRIFLE_ROLLINGBLOCK", "滚轮闭锁式步枪"),
	ItemInfo("WEAPON_REPEATER_EVANS", "埃文斯连发步枪"),
	ItemInfo("WEAPON_BOW", "弓"),
	ItemInfo("WEAPON_REVOLVER_DOUBLEACTION", "双动左轮"),
	ItemInfo("WEAPON_REVOLVER_CATTLEMAN_JOHN", "约翰的左轮"),
	ItemInfo("WEAPON_REVOLVER_CATTLEMAN_MEXICAN", "弗拉科的左轮"),
	ItemInfo("WEAPON_REVOLVER_CATTLEMAN_PIG", "格兰杰的左轮"),
	ItemInfo("WEAPON_REVOLVER_DOUBLEACTION_MICAH", "麦卡的左轮"),
	ItemInfo("WEAPON_REVOLVER_DOUBLEACTION_GAMBLER", "豪客左轮"),
	ItemInfo("WEAPON_REVOLVER_DOUBLEACTION_EXOTIC", "阿尔杰农的左轮"),
	ItemInfo("WEAPON_REVOLVER_SCHOFIELD_CALLOWAY", "卡洛威的左轮"),
	ItemInfo("WEAPON_REVOLVER_SCHOFIELD_GOLDEN", "奥蒂斯·米勒的左轮"),
	ItemInfo("WEAPON_REVOLVER_LEMAT", "勒马特左轮"),
	ItemInfo("WEAPON_REVOLVER_SCHOFIELD", "斯科菲尔德左轮"),
	ItemInfo("WEAPON_PISTOL_VOLCANIC", "火山手枪"),
	ItemInfo("WEAPON_PISTOL_SEMIAUTO", "半自动手枪"),
	ItemInfo("WEAPON_MELEE_KNIFE_JAWBONE", "颚骨刀"),
	ItemInfo("WEAPON_MELEE_KNIFE_JOHN", "约翰的刀"),
	ItemInfo("WEAPON_MELEE_KNIFE_MINER", "宽刃刀"),
	ItemInfo("WEAPON_MELEE_KNIFE_VAMPIRE", "装饰华丽的匕首"),
	ItemInfo("WEAPON_MELEE_KNIFE_BEAR", "角柄刀"),
	ItemInfo("WEAPON_MELEE_HATCHET_VIKING", "维京短斧"),
	ItemInfo("WEAPON_MELEE_HATCHET_HEWING", "劈砍短斧"),
	ItemInfo("WEAPON_MELEE_HATCHET_HUNTER", "猎人短斧"),
	ItemInfo("WEAPON_MELEE_HATCHET_HUNTER_RUSTED", "生锈的猎人短斧"),
	ItemInfo("WEAPON_MELEE_HATCHET_DOUBLE_BIT", "双头短斧"),
	ItemInfo("WEAPON_MELEE_HATCHET_DOUBLE_BIT_RUSTED", "生锈的双头短斧"),
	ItemInfo("WEAPON_THROWN_TOMAHAWK_ANCIENT", "古代手斧"),
	ItemInfo("WEAPON_MELEE_BROKEN_SWORD", "断剑"),
	ItemInfo("WEAPON_MELEE_KNIFE_CIVIL_WAR", "内战刀"),
	ItemInfo("WEAPON_MELEE_ANCIENT_HATCHET", "古斧"),
	ItemInfo("WEAPON_REVOLVER_CATTLEMAN", "牛仔左轮"),
	ItemInfo("WEAPON_THROWN_DYNAMITE", "炸药"),
	ItemInfo("WEAPON_THROWN_DYNAMITE_VOLATILE", "烈性炸药"),
	ItemInfo("WEAPON_THROWN_MOLOTOV", "燃烧瓶"),
	ItemInfo("WEAPON_THROWN_MOLOTOV_VOLATILE", "烈性燃烧瓶"),
	ItemInfo("WEAPON_THROWN_THROWING_KNIVES", "飞刀"),
	ItemInfo("WEAPON_THROWN_TOMAHAWK", "飞斧"),
	ItemInfo("WEAPON_KIT_BINOCULARS", "望远镜"),
	ItemInfo("WEAPON_LASSO", "绳套"),
	ItemInfo("WEAPON_KIT_CAMERA", "照相机"),
	ItemInfo("WEAPON_FISHINGROD", "钓鱼竿"),
	ItemInfo("WEAPON_MOONSHINEJUG", "私酒"),
	ItemInfo("WEAPON_MELEE_CLEAVER", "砍刀"),
	ItemInfo("WEAPON_MELEE_HATCHET", "斧头"),
	ItemInfo("WEAPON_MELEE_KNIFE", "小刀"),
	ItemInfo("WEAPON_MELEE_MACHETE", "大砍刀"),
	ItemInfo("WEAPON_MELEE_TORCH", "火把"),
	ItemInfo("WEAPON_MELEE_LANTERN", "油灯1"),
	ItemInfo("WEAPON_MELEE_DAVY_LANTERN", "油灯2"),
	ItemInfo("WEAPON_MELEE_LANTERN_ELECTRIC", "油灯3"),
};

export ItemInfo WeatherInfos[] = {
	ItemInfo("SUNNY", "晴天"),
	ItemInfo("MISTY", "薄雾"),
	ItemInfo("FOG", "浓雾"),
	ItemInfo("CLOUDS", "多云"),
	ItemInfo("OVERCAST", "阴天"),
	ItemInfo("OVERCASTDARK", "乌云密布"),
	ItemInfo("DRIZZLE", "毛毛雨"),
	ItemInfo("RAIN", "小雨"),
	ItemInfo("THUNDER", "打雷"),
	ItemInfo("THUNDERSTORM", "雷雨交加"),
	ItemInfo("HURRICANE", "飓风"),
	ItemInfo("HIGHPRESSURE", "高压"),
	ItemInfo("SHOWER", "阵雨"),
	ItemInfo("HAIL", "冰雹"),
	ItemInfo("SLEET", "雨夹雪"),
	ItemInfo("SNOWCLEARING", "停止下雪"),
	ItemInfo("SNOWLIGHT", "下雪之夜"),
	ItemInfo("SNOW", "下雪"),
	ItemInfo("BLIZZARD", "暴风雪"),
	ItemInfo("GROUNDBLIZZARD", "地面暴风雪"),
	ItemInfo("WHITEOUT", "乳白天空"),
	ItemInfo("SANDSTORM", "沙尘暴"),
};

export ItemInfo VehicleInfos[] = {
	ItemInfo("gatling_gun", "加特林机枪"),
	ItemInfo("gatlingMaxim02", "马克沁重机枪"),
	ItemInfo("hotAirBalloon01", "热气球"),
	ItemInfo("hotchkiss_cannon", "火炮"),
	ItemInfo("breach_cannon", "意大利炮"),
	ItemInfo("privateopensleeper02x", "privateopensleeper02x"),
	ItemInfo("privateopensleeper01x", "privateopensleeper01x"),
	ItemInfo("STEAMERDUMMY", "STEAMERDUMMY"),
	ItemInfo("armoredCar01x", "armoredCar01x"),
	ItemInfo("armoredCar03x", "armoredCar03x"),
	ItemInfo("privatebaggage01x", "privatebaggage01x"),
	ItemInfo("smuggler02", "smuggler02"),
	ItemInfo("keelboat", "keelboat"),
	ItemInfo("boatSteam02x", "boatSteam02x"),
	ItemInfo("midlandrefrigeratorCar", "midlandrefrigeratorCar"),
	ItemInfo("midlandboxcar05x", "midlandboxcar05x"),
	ItemInfo("CABOOSE01X", "CABOOSE01X"),
	ItemInfo("canoe", "canoe"),
	ItemInfo("canoeTreeTrunk", "canoeTreeTrunk"),
	ItemInfo("cart01", "cart01"),
	ItemInfo("cart02", "cart02"),
	ItemInfo("cart03", "cart03"),
	ItemInfo("cart04", "cart04"),
	ItemInfo("cart05", "cart05"),
	ItemInfo("cart06", "cart06"),
	ItemInfo("cart07", "cart07"),
	ItemInfo("cart08", "cart08"),
	ItemInfo("coach2", "coach2"),
	ItemInfo("coach3", "coach3"),
	ItemInfo("coach3", "coach3"),
	ItemInfo("coach4", "coach4"),
	ItemInfo("coach5", "coach5"),
	ItemInfo("coach6", "coach6"),
	ItemInfo("cart06", "cart06"),
	ItemInfo("cart06", "cart06"),
	ItemInfo("buggy03", "buggy03"),
	ItemInfo("ArmySupplyWagon", "ArmySupplyWagon"),
	ItemInfo("chuckwagon000x", "chuckwagon000x"),
	ItemInfo("chuckwagon000x", "chuckwagon000x"),
	ItemInfo("chuckwagon000x", "chuckwagon000x"),
	ItemInfo("logwagon", "logwagon"),
	ItemInfo("logwagon2", "logwagon2"),
	ItemInfo("coal_wagon", "coal_wagon"),
	ItemInfo("chuckwagon002x", "chuckwagon002x"),
	ItemInfo("handcart", "handcart"),
	ItemInfo("horseBoat", "horseBoat"),
	ItemInfo("mineCart01x", "mineCart01x"),
	ItemInfo("northflatcar01x", "northflatcar01x"),
	ItemInfo("privateflatcar01x", "privateflatcar01x"),
	ItemInfo("northpassenger01x", "northpassenger01x"),
	ItemInfo("northpassenger03x", "northpassenger03x"),
	ItemInfo("privatepassenger01x", "privatepassenger01x"),
	ItemInfo("oilWagon01x", "oilWagon01x"),
	ItemInfo("oilWagon02x", "oilWagon02x"),
	ItemInfo("pirogue", "pirogue"),
	ItemInfo("pirogue2", "pirogue2"),
	ItemInfo("policeWagon01x", "policeWagon01x"),
	ItemInfo("policeWagongatling01x", "policeWagongatling01x"),
	ItemInfo("privateCoalCar01x", "privateCoalCar01x"),
	ItemInfo("NorthCoalCar01x", "NorthCoalCar01x"),
	ItemInfo("winterSteamer", "winterSteamer"),
	ItemInfo("wintercoalcar", "wintercoalcar"),
	ItemInfo("privateboxcar04x", "privateboxcar04x"),
	ItemInfo("privateboxcar02x", "privateboxcar02x"),
	ItemInfo("privateboxcar01x", "privateboxcar01x"),
	ItemInfo("coalHopper01x", "coalHopper01x"),
	ItemInfo("privateObservationcar", "privateObservationcar"),
	ItemInfo("privateArmoured", "privateArmoured"),
	ItemInfo("privateDining01x", "privateDining01x"),
	ItemInfo("privateRooms01x", "privateRooms01x"),
	ItemInfo("privateSteamer01x", "privateSteamer01x"),
	ItemInfo("northSteamer01x", "northSteamer01x"),
	ItemInfo("GhostTrainSteamer", "GhostTrainSteamer"),
	ItemInfo("GhostTrainCoalCar", "GhostTrainCoalCar"),
	ItemInfo("GhostTrainPassenger", "GhostTrainPassenger"),
	ItemInfo("GhostTrainCaboose", "GhostTrainCaboose"),
	ItemInfo("rcBoat", "rcBoat"),
	ItemInfo("rowboat", "rowboat"),
	ItemInfo("rowboatSwamp", "rowboatSwamp"),
	ItemInfo("rowboatSwamp02", "rowboatSwamp02"),
	ItemInfo("ship_guama02", "ship_guama02"),
	ItemInfo("turbineboat", "turbineboat"),
	ItemInfo("ship_nbdGuama", "ship_nbdGuama"),
	ItemInfo("ship_nbdGuama2", "ship_nbdGuama2"),
	ItemInfo("skiff", "skiff"),
	ItemInfo("stagecoach001x", "stagecoach001x"),
	ItemInfo("stagecoach002x", "stagecoach002x"),
	ItemInfo("stagecoach003x", "stagecoach003x"),
	ItemInfo("STAGECOACH004X", "STAGECOACH004X"),
	ItemInfo("stagecoach001x", "stagecoach001x"),
	ItemInfo("stagecoach006x", "stagecoach006x"),
	ItemInfo("TROLLEY01X", "TROLLEY01X"),
	ItemInfo("TugBoat2", "TugBoat2"),
	ItemInfo("wagon02x", "wagon02x"),
	ItemInfo("wagon03x", "wagon03x"),
	ItemInfo("wagon04x", "wagon04x"),
	ItemInfo("wagon05x", "wagon05x"),
	ItemInfo("wagon06x", "wagon06x"),
	ItemInfo("wagonCircus01x", "wagonCircus01x"),
	ItemInfo("wagonCircus02x", "wagonCircus02x"),
	ItemInfo("wagonDoc01x", "wagonDoc01x"),
	ItemInfo("wagonPrison01x", "wagonPrison01x"),
	ItemInfo("wagonWork01x", "wagonWork01x"),
	ItemInfo("wagonDairy01x", "wagonDairy01x"),
	ItemInfo("wagonTraveller01x", "wagonTraveller01x"),
	ItemInfo("utilliwag", "utilliwag"),
	ItemInfo("gatchuck", "gatchuck"),
	ItemInfo("gatchuck_2", "gatchuck_2"),
};